### PR TITLE
Pep code style improvements

### PR DESCRIPTION
**Pull request by rth**
A few minor changes to improve the style of the code ([PEP 0008](https://www.python.org/dev/peps/pep-0008/#whitespace-in-expressions-and-statements)), related to issue #9 :
 
   - renamed the module name to lowercase. So on github it is still called pyBASEX but when installed it is used as,
  
        from  basex import BASEX
      also updated all the examples.

   - added a few more white spaces for readability
   - changed version format from 0.5 to 0.5.0 (usual convention) and added it to the `__init__.py`

### CODE REVIEW

**Comment by DanHickstein** [comment]
These look great! 

Regarding the name-change (lowercase is fine), you've got me thinking - pybasex is actually already a python package. I'll start a separate issue regarding that...

**Comment by DanHickstein** [comment]
Hmmm, so, I think that we need to make the folder lowercase as well. right?

**Comment by rth** [comment]
So it is lowercase in the reposotory. However, I think on local computer you would now have 2 identical folders  `basex` and a `BASEX` , after this PR, where the later is not referenced in git anymore and can be safely deleted. Well that's what I had on my computer anyway, not sure why it happens...

**Comment by DanHickstein** [comment]
Ah, okay, works now.

**Pull request merged**
